### ISSUE TITLE
You book list for this?

### ISSUE THREAD

**Issue by manhnt9** [danielkrakowiak/Engine1#2]
Hello sir. Your work is very admiring.
I want to know about CG books that you've read when implementing the engine.
Thank you.

**Comment by danielkrakowiak** [comment]
Thank you,
I haven't really read any computer graphics books for a long while. I'm reading articles and graphics papers online mostly, watching presentations etc. But it's good to read a book about the graphics API you want to use. One that would explain various concepts and abstractions rather then explaining how to code specific effects. And it's good to read about math - one book I can recommend is "3D Math Primer for Graphics and Game Development". I read it and it helped me a lot.

**Comment by manhnt9** [comment]
I watch presentations too. Articles and papers are still hard for me, I guess I don't have enough basics of CG to read, always stuck at things like rendering algorithm and its math. I'm learning calculus and linear algebra at the uni by the way. Will try "3D Math Primer for Graphics and Game Development" later.

Anyways could you please upload a screenshot of your papers library? Hope that I could know what to read then I can find out what I need to learn to read them :smile:

**Comment by danielkrakowiak** [comment]
Hey,
I exported my bookmarks from chrome. I removed my personal ones, so the
HTML may be broken. But possibly it could be imported in Chrome.

There is lots of stuff :) Some of it is quite old, but it's also good to
learn what kind of problems were important in the past. Obviosuly, I don't
bookmark everything I read, but I try to bookmark interesting or well
written stuff.

Also remeber that you don't need to understand everything from a paper or presentation to learn something. Just try to get an idea of how something works. You can always come back later.

Good luck :)

**Comment by manhnt9** [comment]
Hey I was busy and have just got back to this issue now. 

How do I see the bookmarks?

**Comment by danielkrakowiak** [comment]
Give me your mail and I will send it. I added the attachment, but it got
lost via GitHub.

**Comment by manhnt9** [comment]
My email is ***.
Thank you!

**Comment by manhnt9** [comment]
I received it. Thanks @danielkrakowiak!
